/*=====================================================================
 * BIN2INC.C - turn binary files into wasm DB statements
 *
 *     BIN2INC <out.inc> <label>=<file> [<label>=<file> ...]
 *
 * Each file becomes
 *
 *     <label> label byte
 *             db      0EBh,03Ch,090h, ...
 *     <label>_len equ <n>
 *
 * so the assembler knows both where the data is and how much of it
 * there is.  The length matters: SYS16 pads stage 2 out to its full
 * eight reserved sectors, and it can only do that if it is told how
 * many bytes of real code arrived.
 *
 * Exists because SYS16.COM has to carry the boot sectors inside it
 * (see SYS16.ASM), and wasm has no INCBIN.  Concatenating the raw
 * binaries onto the linked image would work too, but then nothing in
 * the source knows their sizes - and one of them is not a round
 * number of sectors.
 *
 * Built with:  wcl386 -q -bt=nt -fe=bin2inc.exe bin2inc.c
 *=====================================================================*/
#include <stdio.h>
#include <string.h>

#define PERLINE 16

static int emit(FILE *out, const char *label, const char *path)
{
    unsigned char buf[PERLINE];
    unsigned long total = 0;
    size_t n, i;
    FILE *f = fopen(path, "rb");

    if (!f) { perror(path); return 1; }

    fprintf(out, "%s label byte\n", label);
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {
        fputs("        db      ", out);
        for (i = 0; i < n; i++)
            fprintf(out, "%s0%02Xh", i ? "," : "", buf[i]);
        fputc('\n', out);
        total += (unsigned long)n;
    }
    fclose(f);

    if (!total) { fprintf(stderr, "%s: empty\n", path); return 1; }
    fprintf(out, "%s_len equ %lu\n\n", label, total);
    printf("  %-10s %5lu bytes  <- %s\n", label, total, path);
    return 0;
}

int main(int argc, char **argv)
{
    FILE *out;
    int i;

    if (argc < 3) {
        fprintf(stderr, "usage: BIN2INC <out.inc> <label>=<file> ...\n");
        return 1;
    }

    if ((out = fopen(argv[1], "w")) == NULL) { perror(argv[1]); return 1; }
    fprintf(out, ";---------------------------------------------------"
                 "------------------\n"
                 "; %s - GENERATED by TOOLS\\BIN2INC, do not edit\n"
                 ";---------------------------------------------------"
                 "------------------\n\n", argv[1]);

    for (i = 2; i < argc; i++) {
        char label[64];
        char *eq = strchr(argv[i], '=');
        size_t len;

        if (!eq) {
            fprintf(stderr, "%s: expected <label>=<file>\n", argv[i]);
            fclose(out);
            return 1;
        }
        len = (size_t)(eq - argv[i]);
        if (len == 0 || len >= sizeof(label)) {
            fprintf(stderr, "%s: bad label\n", argv[i]);
            fclose(out);
            return 1;
        }
        memcpy(label, argv[i], len);
        label[len] = '\0';

        if (emit(out, label, eq + 1)) { fclose(out); return 1; }
    }

    if (fclose(out)) { perror(argv[1]); return 1; }
    return 0;
}
